name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: write    
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      - name: Install and Build and Test 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - run: yarn install
      - run: npm run ng build -- --base-href="/pdf-key-generator/"
      
      # Add steps for PWA configuration
      - name: Configure PWA with correct base URL
        run: |
          # Create a .htaccess file to ensure proper PWA routing
          echo "RewriteEngine On" > dist/pdf-key-generator/browser/.htaccess
          echo "RewriteBase /pdf-key-generator/" >> dist/pdf-key-generator/browser/.htaccess
          echo "RewriteRule ^index\.html$ - [L]" >> dist/pdf-key-generator/browser/.htaccess
          echo "RewriteCond %{REQUEST_FILENAME} !-f" >> dist/pdf-key-generator/browser/.htaccess
          echo "RewriteCond %{REQUEST_FILENAME} !-d" >> dist/pdf-key-generator/browser/.htaccess
          echo "RewriteRule . /pdf-key-generator/index.html [L]" >> dist/pdf-key-generator/browser/.htaccess
          
          # The ngsw.json file should be properly configured during build, but we can verify it exists
          if [ -f "dist/pdf-key-generator/browser/ngsw.json" ]; then
            echo "Service worker configuration exists"
          else
            echo "Service worker configuration not found - check build settings"
            exit 1
          fi
      
      # - run: npm run ng test -- --browsers ChromeHeadless
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist/pdf-key-generator/browser # The folder the action should deploy.